davglass/license-checker

bin/license-checker
Removes the color tags from chalk when printing out to file using the ‚—out‘ parameter.
=> Remove color tags

lib/index.js
This is only used if you add the --unknown tag.
This is useful as unknown licenses might cause trouble for your software and you.
This will help you to see unknown licenses and have an easier time to grab those dependencies and fix the issue.
The next step is to add an option to only show unknown licenses.
=> Add option to see the path of a dependency if unknown

bin/license-checker, tests/bin-test.js
looks like the latest release is missing a `}`. this adds a test to ensure that `bin/license-checker` exits with code 0 and adds the `}` to make it pass.
=> Ensure bin/license-checker runs

bin/license-checker
The merge in commit 313a7edc3dbdf8d50e43ba8da89306d3c89326bc seems to have been done incorrectly, leading to the output code never to be reached if args.json, args.csv or args.markdown are set.
=> Fix json, csv and markdown output for license-checker

README.md, lib/index.js, package.json
@davglass mentioned moving to [debug](https://www.npmjs.com/package/debug) in #46:
> we should include the `debug` module and then have the flags determine what is shown.
Took a stab at this. It looks like some tests aren’t passing, but I’m guessing that was the case anyway. Have a look and let me know what you think!
=> Add debug for logging

README.md, bin/license-checker, lib/args.js, lib/index.js, tests/test.js
This fixes #52 by adding `--production` and `--development` flags similar to the way that `npm` does it.
=> supporting --production and --development flags

README.md, bin/license-checker, lib/args.js, lib/index.js, package.json, tests/test.js
* Added a relativeLicensePath option to display the license file relatively to the current path.
* Added tests to validate workings
* Updated README
* Added contributor :)
I've used license-checker to export all dependencies + license file locations to a single file, but the paths were absolute: `/Users/sgtdck/Workspace/license-checker/node_modules/yui-lint/LICENSE`. To include this single file in my repo (i.e. 'third party licenses') I had to s/find/replace them.
With the option `--relativeLicensePath` the paths are now displayed relatively to the eldest parent (i.e. dir where `license-checker` is executed.
=> Added a relativeLicensePath option to display the license file relatively to the current path.

bin/license-checker, lib/args.js, lib/index.js
I had a need to output each license as a file. 
Usage: `license-checker --files ./path-to-output-folder`
Unfortunately no unit tests included because this: https://github.com/stjohnjohnson/jenkins-mocha/issues/13
Thanks for the great library!
=> Added ability to output individual license files

README.md
I just added a bit of documentation about the customFormat option.
I noticed that `module_name` is always used in CSV, and that JSON format **adds** the specified fields and do not use them to **replace** the default fields. I could maybe open an issue if someone wants to change that behaviour.
Also, maybe there are other fields that can be used in a custom format (if so, please let me know).
Finally, I saw other available formats in the code (asTree, asMarkDown, ...) that are not listed in the docs so I didn't check anything for them.
=> Add docs about customFormat option

README.md, lib/index.js, tests/config/custom_format_correct.json, tests/test.js
I think that licenseText is useful only for some people. I add them only to custom format.
=> feat: add licenseText only for customFormat

lib/index.js, package.json, tests/fixtures/package.json, tests/test.js
This fixes #70. I've had to include a reference to an invalid syntax somewhere, let me know if I should move the fixture somewhere else.
The new RegEx matches everything that is either not an escaped comma and everything that is an escaped comma, so we have an correct array.
=> fix: allow escaped commas in exclude string

lib/index.js
Eg.
{
"description" : "",
"licenses"    : "",
"repository"  : "",
"licenseFile"     : false,
"licenseText"     : false,
"licenseModified" : false
}
=> Suppress JSON properties with custom format

lib/index.js
This small change is only to have the README value added to the `licenseFile` property.
sample output:
```
{ 'sample_dependency@1.0.0': 
{ licenses: 'MIT*',
licenseFile: '/full path here/sample_dependency/README' } }
```
In some cases we need to have the README associated to `licenseFile`
=> src: the README is added as licenseFile

lib/license.js, tests/fixtures/custom-license-file/package.json, tests/fixtures/custom-license-url/package.json, tests/fixtures/custom-license/package.json, tests/license.js, tests/test.js
The npm package.json spec explains that you can include a string reference to a license that doesn't have an SPDX identifier associated with it. This PR handles some basic examples
=> FEATURE: Recognise some custom licenses

README.md, bin/license-checker, lib/args.js, lib/index.js, tests/failOn-test.js, tests/test.js
The `--failOn [list]` mode is added to be able to use `license-checker` in CI/CD pipelines, e.g. to define the license types that should not be allowed in the final product. 
For example, `license-checker --failOn MIT` should trigger the process to exit with code `1` if the project uses a module which is MIT licensed.
=> Added --failOn [list] mode

lib/index.js, tests/test.js
If a dependency of a dependency has a license we want to dig into, it would be nice to get the exact path of the dependency. Currently, this involves doing a search throughout `node_modules`.
Not all modules have a license file (which displays the location). This PR should resolve this use case for all modules so the path is always available to the user.
Sample output:
```
├─ yargs@3.10.0
│  ├─ licenses: MIT
│  ├─ repository: https://github.com/bcoe/yargs
│  ├─ publisher: Alex Ford
│  ├─ email: Alex.Ford@CodeTunnel.com
│  ├─ url: http://CodeTunnel.com
│  ├─ path: C:\my_module\node_modules\uglify-js\node_modules\yargs
│  └─ licenseFile: C:\my_module\node_modules\uglify-js\node_modules\yargs\LICENSE
```
=> app - output now includes path to dependency.

lib/index.js, tests/failOn-test.js, tests/test.js
Hello! 
Thank you for the handy tool. It has been very useful. I recently started using the only allow option for a project I am working on and ran into a couple of snags. I think I have the solutions for them so I wanted to offer them back to you if you want them. The two issues I ran into were if the licenses had spaces in the name (e.g. "Public Domain") or if the there was a comma (e.g. "Apache License, Version 2.0"). Handling spaces was a fairly straight forward fix. For the commas I changed the separator to a ';'. If that change makes you uncomfortable an option could be added that would allow the user to specify the separator.
=> updated license list parser logic

.travis.yml, README.md
Node 4.x went into maintenance on 2017-04-01 and the maintenance end is scheduled on April 2018, which is in one month. https://en.wikipedia.org/wiki/Node.js#Releases
=> Drop support for node 4, add support for node 8

bin/license-checker, tests/failOn-test.js
I'm not quite sure why it is not failing on the Travis CI, but locally the test failed consistently for me. When I tried it manually, the behavior was correct, but I noticed the test doesn't do exactly what it says. I fixed the tests.
Then I had a thought it would be nice to give warning about the change from commas to semicolons, so I implemented a naive alert to users when they do use commas with the `--failOn` and `--onlyAllow` arguments. I tested this change as well.
=> Fix the "--failOn MIT;ISC" end to end test

lib/index.js, lib/license-files.js, tests/license-files-test.js
- Isolates the license file detection into a separate function (and file)
- Adds unit tests for the detection, verifies some of the issues I filed are not relevant to the license checker
- Adds support for LICENSE-MIT and similar license file names
=> Test and improve detecting license text files

README.md
I did not notice it previously. I added a new one to the top of the README in some of the previous commits.
=> Remove the old status badge

package.json
Before:
```console
> nsp check
(+) 1 vulnerability found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Regular Expression Denial of Service                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ debug                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 3.7 (Low)                                                          │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.6.8                                                              │
├────────────┼───────────────────────────────────────────────────────── …
```
=> fix: Updating debug dependency to fix a security warning

customFormatExample.json, lib/index.js, tests/test.js
Hi @davglass 
very happy to use the license-checker on Node projects. For a current project we need the **copyright statement** for some licenses. 
I started adding this to extend this package for our needs. If you are interested in this feature, We could work on this PR to get it into a "deliverable" stage.
Update: Just saw, this could address issue #154
=> Include Copyright Message in Output

lib/index.js, tests/test.js
This PR fixes that when `--exclude` is added the custom dependencies are also excluded.
Steps to reproduce:
```
git clone git@github.com:mjpearson/passport-wordpress.git
cd passport-wordpress
npm install
license-checker --exclude 'MIT'
```
The output should be the `pkginfo@0.2.3` with a custom license, instead the output is nothing:
After the fix, the output is the right one:
=> Fix exclude not including custom licenses

README.md, bin/license-checker, lib/args.js, lib/index.js, package.json, tests/packages-test.js
Hello everyone and a special hello to @davglass!
Thanks for this amazing package - it helps me not implement a lot of things i'd otherwise have to implement! 👍 
Until now, restricting the generated output to specific packages (and versions) is not possible.
In an environment where a legal department has to check every open source license that is part of a delivered product, the only way to handle this with the current version of `license-checker` is to scan **all** dependencies (including devDependencies).
Using the `--production` switch is not feasible in this scenario, because especially in frontend applications that are built using tooling such as `webpack`, `parcel`, `rollup`, `browserify` or others, the tools unfortunately don't care if a dependency that is included in a build …
=> feat: allow restricting output to specified packages

README.md, bin/license-checker, lib/args.js, lib/index.js, package.json, tests/packages-test.js
This option offers to whitelist some packages. It is useful to exclude private packages, which may come out as UNLICENSED and make the check fail (false positives).
Closes #163 and #171
=> Add an excludePackages option

lib/index.js
Include the name of the package which triggered the error. IMHO this makes it easier to failures:
```
Found license NOT defined by the --onlyAllow flag: "ISC". Exiting.
```
```
Package "foobar@1.0.0" is licensed under "ISC" which is not permitted by the --onlyAllow flag. Exiting.
```
=> Improve --onlyAllow violation Error

bin/license-checker, lib/index.js, package.json
The filtering logic for both `--packages` and `--excludePackages` was broken if the output was being colorized.
To work around this I have moved the colorization out of the parsing logic and into the formatting.
WRT to removing `strip-ansi`, I'm not convinced this package was actually being imported anywhere before this change, but I couldn't find  it referenced anywhere in the code so I've removed it for good hygine.
=> Fixes #177, --packages and --excludePackages filtering

lib/index.js
Moves the `--onlyAllow` and `--failOn` checks so that they are performed after the filtering performed by `--packages` and `--excludePackages`.
=> Fixes 176, Packages are not ignored when using --onlyAllow and --excludePackages

README.md, bin/license-checker, lib/args.js, lib/index.js, tests/packages-test.js
Restricts the output to not include any packages marked as private.
Internal projects typically do not carry any license information, however I do not want to have to ignore 'UNLICENSED' packages, nor do I want to have to meticulously list each module in the list of `--excludedPackages`.
Nb: this PR includes changes from #179
=> Feature: Exclude Private Packages
